---
on:
  workflow_call:
jobs:
  build-gradle:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: 'github'
          settings-path: '${{ github.workspace }}'

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: 'build'
