---
on:
  workflow_call:
jobs:
  publish:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: 'publish'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
