on:
  release:
    types:
      - 'created'
jobs:
  build:
    uses: ./.github/workflows/gradle-build.yml

  publish:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: 'publish -PossrhUsername=${{ github.actor }} -PossrhPassword=${{ secrets.GITHUB_TOKEN }}'
